services:
  api:
    build: api/
    ports:
      - "8099:8099"
    volumes:
      - ./api/config.yaml:/app/config.yaml
      - ./api/data:/app/data
      - ./api/cloud-data:/app/cloud-data
    restart: unless-stopped
    network_mode: host

  app:
    build: app/
    ports:
      - "3000:80"
    restart: unless-stopped

  proxy:
    build:
      context: api/
      dockerfile: Dockerfile.proxy
    ports:
      - "7654:7654"
    volumes:
      - ./api/proxy-config.yaml:/app/proxy-config.yaml
    restart: unless-stopped
    network_mode: host
